name: Test Dispatch

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Test message'
        required: false
        type: string
        default: 'Hello World'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: echo "${{ inputs.message }}"